apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s

    scrape_configs:
      - job_name: otel_collector
        scrape_interval: 5s
        static_configs:
          - targets: ['opentelemetry-collector.dev.svc.cluster.local:8889']

      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:9090' ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          args: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-remote-write-receiver", "--enable-feature=exemplar-storage"]
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: dev
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  # type: LoadBalancer