apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          args: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-remote-write-receiver", "--enable-feature=exemplar-storage"]
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420