apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/fluentbit/fluentbit.yaml
  - deploy/fluentbit/matadata-lua.yaml
  - deploy/grafana/grafana.yaml
  - deploy/loki/loki.yaml
  - deploy/otel/opentelemetry.yaml
  - deploy/prometheus/prometheus.yaml
