# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yburylo13
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.3-77b7d8a"
  arch: amd64

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN

serviceAccount:
  create: false
