name: KBOT-CICD

on:
    push:
      branches:
        - develop

jobs:
    ci:
        permissions:
            contents: 'read'
            id-token: 'write'
      
        name: CI
        runs-on: ubuntu-latest

        steps:

            - uses: 'actions/checkout@v4'
      
            - name: Set up Google Cloud SDK
              uses: google-github-actions/auth@v2
              with:
                    project_id: wise-coyote-417310 
                    credentials_json: ${{ secrets.GCLOUD }}
                    export_default_credentials: true

            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: Run test
              run: make test
            
            - name: Build&Push
              env:
                APP: "kbot"
                REGISTRY: "${{ secrets.GCLOUD_REGISTRY }}"
              run: make image push


            