name: KBOT-CICD

on:
    push:
      branches:
        - develop

jobs:
    ci:
        permissions:
            contents: 'read'
            id-token: 'write'
      
        name: CI
        runs-on: ubuntu-latest

        steps:

            - uses: 'actions/checkout@v4'
      
            - name: Set up Google Cloud SDK
              uses: google-github-actions/auth@v2
              with:
                    project_id: wise-coyote-417310 
                    service_account_key: ${{ secrets.GITHUB_TOKEN }}
                    export_default_credentials: true

            - name: Ceckout
              uses: actions/checkout@v3
            
            - name: Run test
              run: make test

            